### ISSUE TITLE
ELO Colours and Branding

### ISSUE THREAD

**Issue by timwaters** [leidenwarper/mapwarper#7]
System should have similar colours, fonts, icons etc to fit in with existing ELO websites.

**Comment by timwaters** [comment]
![mapwarper](https://cloud.githubusercontent.com/assets/48941/20523147/967f01ae-b0ab-11e6-9022-03170db91ecc.jpg)

**Comment by erfgoedleiden** [comment]
Is it possible to have a default zoom to Leiden, instead of Africa :)  
(52°09'32.2"N 4°29'26.1"E52.158936, 4.490589) 

That would be handy and works quicker, for example when you have to add control points. 
<img width="1248" alt="schermafbeelding 2016-11-24 om 16 22 29" src="https://cloud.githubusercontent.com/assets/13898887/20603553/524e2eb6-b262-11e6-9e6e-2a1adbd7296b.png">

**Comment by timwaters** [comment]
mockup
![mockup_home](https://cloud.githubusercontent.com/assets/48941/20631817/b87ff7a4-b330-11e6-96ae-1e470b7d31ca.jpg)

**Comment by timwaters** [comment]
With flatter tabs 

![screen shot 2016-11-27 at 13 54 31-fullpage](https://cloud.githubusercontent.com/assets/48941/20648824/0d2eea16-b4a9-11e6-94eb-12048705a6c1.png)


![screen shot 2016-11-26 at 17 46 58-fullpage](https://cloud.githubusercontent.com/assets/48941/20642204/8197eb18-b400-11e6-931f-da4f2c6faa5e.png)

**Comment by erfgoedleiden** [comment]
Could you replace the highlight colour (#00f2ab) and borders (green) by ELO-green (#44a140)? For example
![toelichting](https://cloud.githubusercontent.com/assets/13898887/20714278/c5da0304-b64b-11e6-8e97-a919f7155ecb.jpg)
: see image

**Comment by erfgoedleiden** [comment]
could you underline links? That way, it's easier for visitors to understand that they can click on them.

**Comment by timwaters** [comment]
done :-)
